address : 0.0.0.0
port : 8080
maxwoker : 50
maxqueue : 10
clientport : 8989
services:
  10001:
    service: test.service
    point: Test.Service
    address : 127.0.0.1
    port : 8989
  10002:
    service: test.service2
    point: Test.Service2
    address: 127.0.0.1
    port: 8989