address : 0.0.0.0
port : 8080
maxwoker : 50
maxqueue : 10

services:
  10001:
    service: test.service
    point: Test.Service
    address : 192.168.1.10
    port : 8888
  10002:
    service: test.service2
    point: Test.Service2
    address: 192.168.1.15
    port: 9999