// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/midmsg.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rload struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rload) Reset()         { *m = Rload{} }
func (m *Rload) String() string { return proto.CompactTextString(m) }
func (*Rload) ProtoMessage()    {}
func (*Rload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{0}
}

func (m *Rload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rload.Unmarshal(m, b)
}
func (m *Rload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rload.Marshal(b, m, deterministic)
}
func (m *Rload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rload.Merge(m, src)
}
func (m *Rload) XXX_Size() int {
	return xxx_messageInfo_Rload.Size(m)
}
func (m *Rload) XXX_DiscardUnknown() {
	xxx_messageInfo_Rload.DiscardUnknown(m)
}

var xxx_messageInfo_Rload proto.InternalMessageInfo

type NetReqInfo struct {
	M_Body               []byte   `protobuf:"bytes,1,opt,name=m_Body,json=mBody,proto3" json:"m_Body,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetReqInfo) Reset()         { *m = NetReqInfo{} }
func (m *NetReqInfo) String() string { return proto.CompactTextString(m) }
func (*NetReqInfo) ProtoMessage()    {}
func (*NetReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{1}
}

func (m *NetReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetReqInfo.Unmarshal(m, b)
}
func (m *NetReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetReqInfo.Marshal(b, m, deterministic)
}
func (m *NetReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetReqInfo.Merge(m, src)
}
func (m *NetReqInfo) XXX_Size() int {
	return xxx_messageInfo_NetReqInfo.Size(m)
}
func (m *NetReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetReqInfo proto.InternalMessageInfo

func (m *NetReqInfo) GetM_Body() []byte {
	if m != nil {
		return m.M_Body
	}
	return nil
}

func (m *NetReqInfo) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type CallRspInfo struct {
	M_Net_Rsp            []byte   `protobuf:"bytes,1,opt,name=m_Net_Rsp,json=mNetRsp,proto3" json:"m_Net_Rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRspInfo) Reset()         { *m = CallRspInfo{} }
func (m *CallRspInfo) String() string { return proto.CompactTextString(m) }
func (*CallRspInfo) ProtoMessage()    {}
func (*CallRspInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{2}
}

func (m *CallRspInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRspInfo.Unmarshal(m, b)
}
func (m *CallRspInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRspInfo.Marshal(b, m, deterministic)
}
func (m *CallRspInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRspInfo.Merge(m, src)
}
func (m *CallRspInfo) XXX_Size() int {
	return xxx_messageInfo_CallRspInfo.Size(m)
}
func (m *CallRspInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRspInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CallRspInfo proto.InternalMessageInfo

func (m *CallRspInfo) GetM_Net_Rsp() []byte {
	if m != nil {
		return m.M_Net_Rsp
	}
	return nil
}

type NetRspInfo struct {
	M_Net_Rsp            map[uint32]*SendResultInfo `protobuf:"bytes,1,rep,name=m_Net_Rsp,json=mNetRsp,proto3" json:"m_Net_Rsp,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	M_Err                []byte                     `protobuf:"bytes,2,opt,name=m_Err,json=mErr,proto3" json:"m_Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NetRspInfo) Reset()         { *m = NetRspInfo{} }
func (m *NetRspInfo) String() string { return proto.CompactTextString(m) }
func (*NetRspInfo) ProtoMessage()    {}
func (*NetRspInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{3}
}

func (m *NetRspInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetRspInfo.Unmarshal(m, b)
}
func (m *NetRspInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetRspInfo.Marshal(b, m, deterministic)
}
func (m *NetRspInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetRspInfo.Merge(m, src)
}
func (m *NetRspInfo) XXX_Size() int {
	return xxx_messageInfo_NetRspInfo.Size(m)
}
func (m *NetRspInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetRspInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetRspInfo proto.InternalMessageInfo

func (m *NetRspInfo) GetM_Net_Rsp() map[uint32]*SendResultInfo {
	if m != nil {
		return m.M_Net_Rsp
	}
	return nil
}

func (m *NetRspInfo) GetM_Err() []byte {
	if m != nil {
		return m.M_Err
	}
	return nil
}

type SendResultInfo struct {
	Key                  uint32                       `protobuf:"varint,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	SendCount            int32                        `protobuf:"varint,2,opt,name=SendCount,json=sendCount,proto3" json:"SendCount,omitempty"`
	SuccessCount         int32                        `protobuf:"varint,3,opt,name=SuccessCount,json=successCount,proto3" json:"SuccessCount,omitempty"`
	FailCount            int32                        `protobuf:"varint,4,opt,name=FailCount,json=failCount,proto3" json:"FailCount,omitempty"`
	DiscardCount         int32                        `protobuf:"varint,5,opt,name=DiscardCount,json=discardCount,proto3" json:"DiscardCount,omitempty"`
	ReSendCount          int32                        `protobuf:"varint,6,opt,name=ReSendCount,json=reSendCount,proto3" json:"ReSendCount,omitempty"`
	CheckErr             []byte                       `protobuf:"bytes,7,opt,name=CheckErr,json=checkErr,proto3" json:"CheckErr,omitempty"`
	ResultList           map[uint32]*SingleResultInfo `protobuf:"bytes,8,rep,name=ResultList,json=resultList,proto3" json:"ResultList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SendResultInfo) Reset()         { *m = SendResultInfo{} }
func (m *SendResultInfo) String() string { return proto.CompactTextString(m) }
func (*SendResultInfo) ProtoMessage()    {}
func (*SendResultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{4}
}

func (m *SendResultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResultInfo.Unmarshal(m, b)
}
func (m *SendResultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResultInfo.Marshal(b, m, deterministic)
}
func (m *SendResultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResultInfo.Merge(m, src)
}
func (m *SendResultInfo) XXX_Size() int {
	return xxx_messageInfo_SendResultInfo.Size(m)
}
func (m *SendResultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SendResultInfo proto.InternalMessageInfo

func (m *SendResultInfo) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *SendResultInfo) GetSendCount() int32 {
	if m != nil {
		return m.SendCount
	}
	return 0
}

func (m *SendResultInfo) GetSuccessCount() int32 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *SendResultInfo) GetFailCount() int32 {
	if m != nil {
		return m.FailCount
	}
	return 0
}

func (m *SendResultInfo) GetDiscardCount() int32 {
	if m != nil {
		return m.DiscardCount
	}
	return 0
}

func (m *SendResultInfo) GetReSendCount() int32 {
	if m != nil {
		return m.ReSendCount
	}
	return 0
}

func (m *SendResultInfo) GetCheckErr() []byte {
	if m != nil {
		return m.CheckErr
	}
	return nil
}

func (m *SendResultInfo) GetResultList() map[uint32]*SingleResultInfo {
	if m != nil {
		return m.ResultList
	}
	return nil
}

type SingleResultInfo struct {
	AskSequence          uint64   `protobuf:"varint,1,opt,name=AskSequence,json=askSequence,proto3" json:"AskSequence,omitempty"`
	SendTimeApp          uint64   `protobuf:"varint,2,opt,name=SendTimeApp,json=sendTimeApp,proto3" json:"SendTimeApp,omitempty"`
	MsgType              int32    `protobuf:"varint,3,opt,name=MsgType,json=msgType,proto3" json:"MsgType,omitempty"`
	MsgAckType           int32    `protobuf:"varint,4,opt,name=MsgAckType,json=msgAckType,proto3" json:"MsgAckType,omitempty"`
	SyncType             uint32   `protobuf:"varint,5,opt,name=SyncType,json=syncType,proto3" json:"SyncType,omitempty"`
	IsTimeOut            bool     `protobuf:"varint,6,opt,name=IsTimeOut,json=isTimeOut,proto3" json:"IsTimeOut,omitempty"`
	IsDisCard            bool     `protobuf:"varint,7,opt,name=IsDisCard,json=isDisCard,proto3" json:"IsDisCard,omitempty"`
	IsResend             bool     `protobuf:"varint,8,opt,name=IsResend,json=isResend,proto3" json:"IsResend,omitempty"`
	Errinfo              []byte   `protobuf:"bytes,9,opt,name=Errinfo,json=errinfo,proto3" json:"Errinfo,omitempty"`
	Result               []byte   `protobuf:"bytes,10,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleResultInfo) Reset()         { *m = SingleResultInfo{} }
func (m *SingleResultInfo) String() string { return proto.CompactTextString(m) }
func (*SingleResultInfo) ProtoMessage()    {}
func (*SingleResultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{5}
}

func (m *SingleResultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleResultInfo.Unmarshal(m, b)
}
func (m *SingleResultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleResultInfo.Marshal(b, m, deterministic)
}
func (m *SingleResultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleResultInfo.Merge(m, src)
}
func (m *SingleResultInfo) XXX_Size() int {
	return xxx_messageInfo_SingleResultInfo.Size(m)
}
func (m *SingleResultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleResultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SingleResultInfo proto.InternalMessageInfo

func (m *SingleResultInfo) GetAskSequence() uint64 {
	if m != nil {
		return m.AskSequence
	}
	return 0
}

func (m *SingleResultInfo) GetSendTimeApp() uint64 {
	if m != nil {
		return m.SendTimeApp
	}
	return 0
}

func (m *SingleResultInfo) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *SingleResultInfo) GetMsgAckType() int32 {
	if m != nil {
		return m.MsgAckType
	}
	return 0
}

func (m *SingleResultInfo) GetSyncType() uint32 {
	if m != nil {
		return m.SyncType
	}
	return 0
}

func (m *SingleResultInfo) GetIsTimeOut() bool {
	if m != nil {
		return m.IsTimeOut
	}
	return false
}

func (m *SingleResultInfo) GetIsDisCard() bool {
	if m != nil {
		return m.IsDisCard
	}
	return false
}

func (m *SingleResultInfo) GetIsResend() bool {
	if m != nil {
		return m.IsResend
	}
	return false
}

func (m *SingleResultInfo) GetErrinfo() []byte {
	if m != nil {
		return m.Errinfo
	}
	return nil
}

func (m *SingleResultInfo) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type ClientRsqInfo struct {
	M_Resp               []byte   `protobuf:"bytes,1,opt,name=m_Resp,json=mResp,proto3" json:"m_Resp,omitempty"`
	M_Type               uint32   `protobuf:"varint,2,opt,name=m_Type,json=mType,proto3" json:"m_Type,omitempty"`
	M_RqId               string   `protobuf:"bytes,3,opt,name=m_RqId,json=mRqId,proto3" json:"m_RqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRsqInfo) Reset()         { *m = ClientRsqInfo{} }
func (m *ClientRsqInfo) String() string { return proto.CompactTextString(m) }
func (*ClientRsqInfo) ProtoMessage()    {}
func (*ClientRsqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{6}
}

func (m *ClientRsqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRsqInfo.Unmarshal(m, b)
}
func (m *ClientRsqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRsqInfo.Marshal(b, m, deterministic)
}
func (m *ClientRsqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRsqInfo.Merge(m, src)
}
func (m *ClientRsqInfo) XXX_Size() int {
	return xxx_messageInfo_ClientRsqInfo.Size(m)
}
func (m *ClientRsqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRsqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRsqInfo proto.InternalMessageInfo

func (m *ClientRsqInfo) GetM_Resp() []byte {
	if m != nil {
		return m.M_Resp
	}
	return nil
}

func (m *ClientRsqInfo) GetM_Type() uint32 {
	if m != nil {
		return m.M_Type
	}
	return 0
}

func (m *ClientRsqInfo) GetM_RqId() string {
	if m != nil {
		return m.M_RqId
	}
	return ""
}

type GJ_Net_Pack struct {
	M_Net_Pack           map[uint32]*Net_Pack `protobuf:"bytes,1,rep,name=m_Net_Pack,json=mNetPack,proto3" json:"m_Net_Pack,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GJ_Net_Pack) Reset()         { *m = GJ_Net_Pack{} }
func (m *GJ_Net_Pack) String() string { return proto.CompactTextString(m) }
func (*GJ_Net_Pack) ProtoMessage()    {}
func (*GJ_Net_Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{7}
}

func (m *GJ_Net_Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GJ_Net_Pack.Unmarshal(m, b)
}
func (m *GJ_Net_Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GJ_Net_Pack.Marshal(b, m, deterministic)
}
func (m *GJ_Net_Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GJ_Net_Pack.Merge(m, src)
}
func (m *GJ_Net_Pack) XXX_Size() int {
	return xxx_messageInfo_GJ_Net_Pack.Size(m)
}
func (m *GJ_Net_Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_GJ_Net_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_GJ_Net_Pack proto.InternalMessageInfo

func (m *GJ_Net_Pack) GetM_Net_Pack() map[uint32]*Net_Pack {
	if m != nil {
		return m.M_Net_Pack
	}
	return nil
}

type Net_Pack struct {
	M_Msg                []byte                    `protobuf:"bytes,1,opt,name=m_Msg,json=mMsg,proto3" json:"m_Msg,omitempty"`
	M_MsgBody            *Net_Pack_Min_Net_MsgBody `protobuf:"bytes,2,opt,name=m_MsgBody,json=mMsgBody,proto3" json:"m_MsgBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Net_Pack) Reset()         { *m = Net_Pack{} }
func (m *Net_Pack) String() string { return proto.CompactTextString(m) }
func (*Net_Pack) ProtoMessage()    {}
func (*Net_Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{8}
}

func (m *Net_Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net_Pack.Unmarshal(m, b)
}
func (m *Net_Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net_Pack.Marshal(b, m, deterministic)
}
func (m *Net_Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net_Pack.Merge(m, src)
}
func (m *Net_Pack) XXX_Size() int {
	return xxx_messageInfo_Net_Pack.Size(m)
}
func (m *Net_Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_Net_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_Net_Pack proto.InternalMessageInfo

func (m *Net_Pack) GetM_Msg() []byte {
	if m != nil {
		return m.M_Msg
	}
	return nil
}

func (m *Net_Pack) GetM_MsgBody() *Net_Pack_Min_Net_MsgBody {
	if m != nil {
		return m.M_MsgBody
	}
	return nil
}

type Net_Pack_Min_Net_MsgBody struct {
	MLAsktype            uint64   `protobuf:"varint,1,opt,name=m_lAsktype,json=mLAsktype,proto3" json:"m_lAsktype,omitempty"`
	MLServerSequence     uint64   `protobuf:"varint,2,opt,name=m_lServerSequence,json=mLServerSequence,proto3" json:"m_lServerSequence,omitempty"`
	MLAskSequence        uint64   `protobuf:"varint,3,opt,name=m_lAskSequence,json=mLAskSequence,proto3" json:"m_lAskSequence,omitempty"`
	MCMsgAckType         int32    `protobuf:"varint,4,opt,name=m_cMsgAckType,json=mCMsgAckType,proto3" json:"m_cMsgAckType,omitempty"`
	MCMsgType            int32    `protobuf:"varint,5,opt,name=m_cMsgType,json=mCMsgType,proto3" json:"m_cMsgType,omitempty"`
	MSSendCount          int32    `protobuf:"varint,6,opt,name=m_sSendCount,json=mSSendCount,proto3" json:"m_sSendCount,omitempty"`
	MLExpireTime         uint32   `protobuf:"varint,7,opt,name=m_lExpireTime,json=mLExpireTime,proto3" json:"m_lExpireTime,omitempty"`
	MISendTimeApp        uint64   `protobuf:"varint,8,opt,name=m_iSendTimeApp,json=mISendTimeApp,proto3" json:"m_iSendTimeApp,omitempty"`
	MLResult             int32    `protobuf:"varint,9,opt,name=m_lResult,json=mLResult,proto3" json:"m_lResult,omitempty"`
	MLBack               uint64   `protobuf:"varint,10,opt,name=m_lBack,json=mLBack,proto3" json:"m_lBack,omitempty"`
	MIDiscard            int32    `protobuf:"varint,11,opt,name=m_iDiscard,json=mIDiscard,proto3" json:"m_iDiscard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net_Pack_Min_Net_MsgBody) Reset()         { *m = Net_Pack_Min_Net_MsgBody{} }
func (m *Net_Pack_Min_Net_MsgBody) String() string { return proto.CompactTextString(m) }
func (*Net_Pack_Min_Net_MsgBody) ProtoMessage()    {}
func (*Net_Pack_Min_Net_MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_7304c339219e1145, []int{8, 0}
}

func (m *Net_Pack_Min_Net_MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net_Pack_Min_Net_MsgBody.Unmarshal(m, b)
}
func (m *Net_Pack_Min_Net_MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net_Pack_Min_Net_MsgBody.Marshal(b, m, deterministic)
}
func (m *Net_Pack_Min_Net_MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net_Pack_Min_Net_MsgBody.Merge(m, src)
}
func (m *Net_Pack_Min_Net_MsgBody) XXX_Size() int {
	return xxx_messageInfo_Net_Pack_Min_Net_MsgBody.Size(m)
}
func (m *Net_Pack_Min_Net_MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_Net_Pack_Min_Net_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_Net_Pack_Min_Net_MsgBody proto.InternalMessageInfo

func (m *Net_Pack_Min_Net_MsgBody) GetMLAsktype() uint64 {
	if m != nil {
		return m.MLAsktype
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMLServerSequence() uint64 {
	if m != nil {
		return m.MLServerSequence
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMLAskSequence() uint64 {
	if m != nil {
		return m.MLAskSequence
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMCMsgAckType() int32 {
	if m != nil {
		return m.MCMsgAckType
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMCMsgType() int32 {
	if m != nil {
		return m.MCMsgType
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMSSendCount() int32 {
	if m != nil {
		return m.MSSendCount
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMLExpireTime() uint32 {
	if m != nil {
		return m.MLExpireTime
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMISendTimeApp() uint64 {
	if m != nil {
		return m.MISendTimeApp
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMLResult() int32 {
	if m != nil {
		return m.MLResult
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMLBack() uint64 {
	if m != nil {
		return m.MLBack
	}
	return 0
}

func (m *Net_Pack_Min_Net_MsgBody) GetMIDiscard() int32 {
	if m != nil {
		return m.MIDiscard
	}
	return 0
}

func init() {
	proto.RegisterType((*Rload)(nil), "proto.Rload")
	proto.RegisterType((*NetReqInfo)(nil), "proto.NetReqInfo")
	proto.RegisterType((*CallRspInfo)(nil), "proto.CallRspInfo")
	proto.RegisterType((*NetRspInfo)(nil), "proto.NetRspInfo")
	proto.RegisterMapType((map[uint32]*SendResultInfo)(nil), "proto.NetRspInfo.MNetRspEntry")
	proto.RegisterType((*SendResultInfo)(nil), "proto.SendResultInfo")
	proto.RegisterMapType((map[uint32]*SingleResultInfo)(nil), "proto.SendResultInfo.ResultListEntry")
	proto.RegisterType((*SingleResultInfo)(nil), "proto.SingleResultInfo")
	proto.RegisterType((*ClientRsqInfo)(nil), "proto.ClientRsqInfo")
	proto.RegisterType((*GJ_Net_Pack)(nil), "proto.GJ_Net_Pack")
	proto.RegisterMapType((map[uint32]*Net_Pack)(nil), "proto.GJ_Net_Pack.MNetPackEntry")
	proto.RegisterType((*Net_Pack)(nil), "proto.Net_Pack")
	proto.RegisterType((*Net_Pack_Min_Net_MsgBody)(nil), "proto.Net_Pack.Min_Net_MsgBody")
}

func init() { proto.RegisterFile("proto/midmsg.proto", fileDescriptor_7304c339219e1145) }

var fileDescriptor_7304c339219e1145 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdf, 0x6e, 0xe3, 0x44,
	0x17, 0x6f, 0x9a, 0x38, 0xb1, 0x8f, 0x9d, 0x6d, 0x3b, 0x9f, 0xf6, 0xdb, 0x28, 0xc0, 0x52, 0x8c,
	0x2a, 0x15, 0x2d, 0xa4, 0xa2, 0xdc, 0xa0, 0x15, 0x20, 0x65, 0xb3, 0x01, 0x05, 0x92, 0x65, 0x99,
	0x54, 0xdc, 0x46, 0x59, 0x7b, 0x9a, 0x1d, 0xc5, 0xe3, 0xa4, 0x1e, 0xa7, 0xa2, 0x12, 0x77, 0xdc,
	0xf2, 0x06, 0xbc, 0x04, 0x57, 0x3c, 0x06, 0x4f, 0xc2, 0x43, 0xa0, 0x39, 0x67, 0x62, 0x3b, 0x6d,
	0x90, 0xe0, 0xca, 0x3e, 0xbf, 0xf3, 0x9b, 0xf3, 0x67, 0xce, 0x99, 0x73, 0x80, 0xad, 0xb3, 0x55,
	0xbe, 0xba, 0x50, 0x32, 0x56, 0x7a, 0xd1, 0x43, 0x81, 0x39, 0xf8, 0x09, 0x5b, 0xe0, 0xf0, 0x64,
	0x35, 0x8f, 0xc3, 0x2f, 0x01, 0x5e, 0x89, 0x9c, 0x8b, 0x9b, 0x51, 0x7a, 0xbd, 0x62, 0x8f, 0xa1,
	0xa9, 0x66, 0x2f, 0x56, 0xf1, 0x5d, 0xa7, 0x76, 0x5a, 0x3b, 0x0f, 0xb8, 0xa3, 0x8c, 0xc0, 0x3a,
	0xd0, 0xd2, 0x22, 0xbb, 0x95, 0x91, 0xe8, 0x1c, 0x9e, 0xd6, 0xce, 0x3d, 0xbe, 0x15, 0xc3, 0x8f,
	0xc0, 0x1f, 0xcc, 0x93, 0x84, 0xeb, 0x35, 0x9e, 0xef, 0x82, 0xa7, 0x66, 0xaf, 0x44, 0x3e, 0xe3,
	0x7a, 0x6d, 0x4d, 0xb4, 0x94, 0xb1, 0xaf, 0xd7, 0xe1, 0xef, 0x35, 0x72, 0x65, 0xa9, 0xcf, 0x77,
	0xa9, 0xf5, 0x73, 0xff, 0xf2, 0x29, 0xc5, 0xd8, 0x2b, 0x59, 0xbd, 0x09, 0xfd, 0x0f, 0xd3, 0x3c,
	0xbb, 0x2b, 0x4c, 0xb1, 0xff, 0x81, 0xa3, 0x66, 0xc3, 0x2c, 0xc3, 0x68, 0x02, 0xde, 0x50, 0xc3,
	0x2c, 0xeb, 0xfe, 0x00, 0x41, 0x95, 0xcd, 0x8e, 0xa1, 0xbe, 0x14, 0x94, 0x48, 0x9b, 0x9b, 0x5f,
	0xf6, 0x0c, 0x9c, 0xdb, 0x79, 0xb2, 0xa1, 0x24, 0xfc, 0xcb, 0xc7, 0xd6, 0xdd, 0x54, 0xa4, 0x31,
	0x17, 0x7a, 0x93, 0xe4, 0xc6, 0x25, 0x27, 0xce, 0xf3, 0xc3, 0xcf, 0x6b, 0xe1, 0x2f, 0x75, 0x78,
	0xb4, 0xab, 0x35, 0x56, 0xbf, 0xdb, 0xb5, 0xfa, 0x2e, 0x78, 0x86, 0x33, 0x58, 0x6d, 0xd2, 0x1c,
	0x2d, 0x3b, 0xdc, 0xd3, 0x5b, 0x80, 0x85, 0x10, 0x4c, 0x37, 0x51, 0x24, 0xb4, 0x26, 0x42, 0x1d,
	0x09, 0x81, 0xae, 0x60, 0xc6, 0xc2, 0xd7, 0x73, 0x99, 0x10, 0xa1, 0x41, 0x16, 0xae, 0xb7, 0x80,
	0xb1, 0xf0, 0x52, 0xea, 0x68, 0x9e, 0x59, 0x17, 0x0e, 0x59, 0x88, 0x2b, 0x18, 0x3b, 0x05, 0x9f,
	0x8b, 0x32, 0x8a, 0x26, 0x52, 0xfc, 0xac, 0x84, 0x58, 0x17, 0xdc, 0xc1, 0x5b, 0x11, 0x2d, 0xcd,
	0xad, 0xb5, 0xf0, 0xd6, 0xdc, 0xc8, 0xca, 0x6c, 0x08, 0x40, 0x19, 0x8e, 0xa5, 0xce, 0x3b, 0x2e,
	0xd6, 0xe2, 0x6c, 0xef, 0xe5, 0xf4, 0x4a, 0x1e, 0x95, 0x04, 0xb2, 0x02, 0xe8, 0xfe, 0x08, 0x47,
	0xf7, 0xd4, 0x7b, 0x6a, 0xf0, 0xc9, 0x6e, 0x0d, 0x9e, 0x6c, 0xdd, 0xc8, 0x74, 0x91, 0x88, 0xfd,
	0x55, 0xf8, 0xe3, 0x10, 0x8e, 0xef, 0xeb, 0x4d, 0xc6, 0x7d, 0xbd, 0x9c, 0x8a, 0x9b, 0x8d, 0x48,
	0x23, 0x81, 0x1e, 0x1a, 0xdc, 0x9f, 0x97, 0x90, 0x61, 0x98, 0xe0, 0xaf, 0xa4, 0x12, 0xfd, 0xf5,
	0x1a, 0xfd, 0x35, 0xb8, 0xaf, 0x4b, 0xc8, 0xb4, 0xf5, 0x44, 0x2f, 0xae, 0xee, 0xd6, 0xc2, 0x96,
	0xa5, 0xa5, 0x48, 0x64, 0x4f, 0x01, 0x26, 0x7a, 0xd1, 0x8f, 0x96, 0xa8, 0xa4, 0x92, 0x80, 0x2a,
	0x10, 0x73, 0x9b, 0xd3, 0xbb, 0x34, 0x42, 0xad, 0x83, 0xc9, 0xb9, 0xda, 0xca, 0xa6, 0x9a, 0x23,
	0x6d, 0x5c, 0x7c, 0xbf, 0xa1, 0x4a, 0xb8, 0xdc, 0x93, 0x5b, 0x80, 0xb4, 0x2f, 0xa5, 0x1e, 0xcc,
	0xb3, 0x18, 0x0b, 0x81, 0x5a, 0x0b, 0x18, 0xbb, 0x23, 0xcd, 0x85, 0x09, 0xb2, 0xe3, 0xa2, 0xd2,
	0x95, 0x56, 0x36, 0xd1, 0x0e, 0xb3, 0x4c, 0xa6, 0xd7, 0xab, 0x8e, 0x47, 0x2f, 0x4b, 0x90, 0xc8,
	0xfe, 0x0f, 0x4d, 0xba, 0x99, 0x0e, 0xa0, 0xa2, 0x49, 0x45, 0x09, 0xaf, 0xa0, 0x3d, 0x48, 0xa4,
	0x48, 0x73, 0xae, 0x2b, 0xcf, 0x9b, 0x8b, 0xe2, 0x6d, 0x3a, 0xca, 0x08, 0x04, 0x63, 0x2e, 0x87,
	0x98, 0x8b, 0xa3, 0x30, 0x11, 0x62, 0xdf, 0x8c, 0x62, 0xbc, 0x1d, 0xcf, 0xb0, 0x6f, 0x46, 0x71,
	0xf8, 0x5b, 0x0d, 0xfc, 0x6f, 0xbe, 0xc5, 0xa7, 0xfb, 0x7a, 0x1e, 0x2d, 0xd9, 0x57, 0x00, 0xaa,
	0x90, 0xec, 0x4b, 0x3e, 0xb5, 0x65, 0xad, 0xf0, 0xf0, 0x29, 0x9b, 0x1f, 0x6a, 0x1c, 0x57, 0x59,
	0xb1, 0x3b, 0x86, 0xf6, 0x8e, 0x6a, 0x4f, 0xd3, 0x9c, 0xed, 0x36, 0xcd, 0x51, 0x39, 0x27, 0xd0,
	0x74, 0xb5, 0x59, 0xfe, 0xaa, 0x83, 0x5b, 0x84, 0x86, 0x73, 0x62, 0xa2, 0x17, 0x36, 0xdd, 0x86,
	0x9a, 0xe8, 0x05, 0xfb, 0xc2, 0x0c, 0x9e, 0x89, 0x5e, 0xe0, 0x98, 0x23, 0x83, 0xef, 0xdf, 0x33,
	0xd8, 0x9b, 0xc8, 0x14, 0x03, 0xb7, 0x34, 0xee, 0x2a, 0xfb, 0xd7, 0xfd, 0xb5, 0x0e, 0x47, 0xf7,
	0xb4, 0xec, 0x3d, 0x73, 0x03, 0x49, 0x5f, 0x2f, 0x73, 0x73, 0x87, 0xd4, 0x8a, 0x9e, 0x1a, 0x5b,
	0x80, 0x3d, 0x83, 0x13, 0x35, 0x4b, 0xa6, 0x22, 0xbb, 0x15, 0x59, 0xd1, 0xb0, 0xd4, 0x8e, 0xc7,
	0x6a, 0xbc, 0x8b, 0xb3, 0x33, 0x78, 0x44, 0xb6, 0x0a, 0x66, 0x1d, 0x99, 0x6d, 0xb4, 0x57, 0xd0,
	0x3e, 0x84, 0xb6, 0x9a, 0x45, 0x0f, 0x7a, 0x34, 0x50, 0x83, 0x12, 0xa3, 0xb8, 0xa2, 0x6d, 0x8b,
	0xd3, 0xdc, 0xf0, 0x90, 0x81, 0xea, 0x0f, 0x20, 0x50, 0x33, 0xfd, 0x60, 0x6a, 0xa8, 0x69, 0x39,
	0x35, 0xd0, 0x4d, 0x32, 0xfc, 0x69, 0x2d, 0x33, 0x61, 0x3a, 0x18, 0x3b, 0xb6, 0xcd, 0x03, 0x35,
	0x2e, 0x31, 0x0a, 0x59, 0x56, 0xdf, 0x9a, 0x6b, 0x43, 0x1e, 0x55, 0x40, 0xf6, 0x8e, 0xb9, 0xf7,
	0xc4, 0x36, 0xaa, 0x87, 0xbe, 0x5c, 0x35, 0x26, 0x99, 0x3d, 0x81, 0x96, 0x9a, 0x25, 0x2f, 0x4c,
	0x07, 0x01, 0x1e, 0x6e, 0xaa, 0xb1, 0x91, 0x28, 0x07, 0x69, 0x07, 0x60, 0xc7, 0xb7, 0x39, 0x8c,
	0x2c, 0x70, 0xf9, 0x67, 0x0d, 0x60, 0x22, 0xe3, 0x29, 0xad, 0x23, 0xd6, 0x83, 0x86, 0x79, 0x97,
	0xec, 0xa4, 0xb2, 0x49, 0x68, 0xb5, 0x75, 0x4f, 0x1e, 0x2c, 0x97, 0xf0, 0x80, 0x5d, 0x80, 0xd3,
	0xd7, 0xff, 0xe5, 0xc0, 0xa7, 0xd0, 0x7a, 0xbd, 0x79, 0x93, 0x48, 0xfd, 0xf6, 0x5f, 0x1f, 0xf9,
	0x18, 0x02, 0x2e, 0xcc, 0xae, 0x1d, 0xac, 0xd2, 0x6b, 0xb9, 0x60, 0x81, 0x25, 0xe1, 0xfe, 0xed,
	0xee, 0x48, 0xe1, 0xc1, 0xe5, 0xcf, 0xdb, 0x37, 0xbb, 0x4d, 0xe9, 0x02, 0x1a, 0x66, 0xc3, 0xee,
	0x73, 0xc7, 0x2c, 0x54, 0xd9, 0xc0, 0xe1, 0x81, 0x59, 0xac, 0x98, 0x13, 0x9e, 0xfa, 0xa7, 0xf9,
	0xba, 0xff, 0xec, 0x9b, 0x26, 0x82, 0x9f, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xf2, 0x18,
	0xc4, 0x3a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MidServiceClient is the client API for MidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MidServiceClient interface {
	Sync(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error)
	Async(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error)
	Publish(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error)
	ReloadConfig(ctx context.Context, in *Rload, opts ...grpc.CallOption) (*Rload, error)
}

type midServiceClient struct {
	cc *grpc.ClientConn
}

func NewMidServiceClient(cc *grpc.ClientConn) MidServiceClient {
	return &midServiceClient{cc}
}

func (c *midServiceClient) Sync(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error) {
	out := new(NetRspInfo)
	err := c.cc.Invoke(ctx, "/proto.MidService/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midServiceClient) Async(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error) {
	out := new(NetRspInfo)
	err := c.cc.Invoke(ctx, "/proto.MidService/Async", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midServiceClient) Publish(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*NetRspInfo, error) {
	out := new(NetRspInfo)
	err := c.cc.Invoke(ctx, "/proto.MidService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midServiceClient) ReloadConfig(ctx context.Context, in *Rload, opts ...grpc.CallOption) (*Rload, error) {
	out := new(Rload)
	err := c.cc.Invoke(ctx, "/proto.MidService/ReloadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MidServiceServer is the server API for MidService service.
type MidServiceServer interface {
	Sync(context.Context, *NetReqInfo) (*NetRspInfo, error)
	Async(context.Context, *NetReqInfo) (*NetRspInfo, error)
	Publish(context.Context, *NetReqInfo) (*NetRspInfo, error)
	ReloadConfig(context.Context, *Rload) (*Rload, error)
}

// UnimplementedMidServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMidServiceServer struct {
}

func (*UnimplementedMidServiceServer) Sync(ctx context.Context, req *NetReqInfo) (*NetRspInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedMidServiceServer) Async(ctx context.Context, req *NetReqInfo) (*NetRspInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Async not implemented")
}
func (*UnimplementedMidServiceServer) Publish(ctx context.Context, req *NetReqInfo) (*NetRspInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedMidServiceServer) ReloadConfig(ctx context.Context, req *Rload) (*Rload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}

func RegisterMidServiceServer(s *grpc.Server, srv MidServiceServer) {
	s.RegisterService(&_MidService_serviceDesc, srv)
}

func _MidService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MidService/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidServiceServer).Sync(ctx, req.(*NetReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidService_Async_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidServiceServer).Async(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MidService/Async",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidServiceServer).Async(ctx, req.(*NetReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MidService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidServiceServer).Publish(ctx, req.(*NetReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MidService/ReloadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidServiceServer).ReloadConfig(ctx, req.(*Rload))
	}
	return interceptor(ctx, in, info, handler)
}

var _MidService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MidService",
	HandlerType: (*MidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _MidService_Sync_Handler,
		},
		{
			MethodName: "Async",
			Handler:    _MidService_Async_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _MidService_Publish_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _MidService_ReloadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/midmsg.proto",
}

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	Call(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*CallRspInfo, error)
	AsyncCall(ctx context.Context, in *SingleResultInfo, opts ...grpc.CallOption) (*CallRspInfo, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) Call(ctx context.Context, in *NetReqInfo, opts ...grpc.CallOption) (*CallRspInfo, error) {
	out := new(CallRspInfo)
	err := c.cc.Invoke(ctx, "/proto.ClientService/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) AsyncCall(ctx context.Context, in *SingleResultInfo, opts ...grpc.CallOption) (*CallRspInfo, error) {
	out := new(CallRspInfo)
	err := c.cc.Invoke(ctx, "/proto.ClientService/AsyncCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	Call(context.Context, *NetReqInfo) (*CallRspInfo, error)
	AsyncCall(context.Context, *SingleResultInfo) (*CallRspInfo, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) Call(ctx context.Context, req *NetReqInfo) (*CallRspInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedClientServiceServer) AsyncCall(ctx context.Context, req *SingleResultInfo) (*CallRspInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsyncCall not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetReqInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClientService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).Call(ctx, req.(*NetReqInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_AsyncCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleResultInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).AsyncCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClientService/AsyncCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).AsyncCall(ctx, req.(*SingleResultInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _ClientService_Call_Handler,
		},
		{
			MethodName: "AsyncCall",
			Handler:    _ClientService_AsyncCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/midmsg.proto",
}
